### PR TITLE
adding new Email Template

### PR DESCRIPTION
**Pull request by kazekagegaara**
Commit for Style the Alert Emails #76

### CODE REVIEW

**Comment by tidusjar** [comment]
The `@Model` is the model passed in from the server side, it contains the information about the duration, percentage etc :+1:  Once you have got those changes it should be cool :) 
Thanks!

**Comment by kazekagegaara** [comment]
@tidusjar my bad, almost no experience with C# stuff. I'll make these changes. Question about the workflow, so I make changes on my fork, push it and then how do I link that with this PR?

**Comment by tidusjar** [comment]
That's fine! Yes, make the changes in your fork and then commit it and I'm pretty sure it will appear in this PR

**Comment by kazekagegaara** [comment]
Done. Please review.

**Comment by tidusjar** [comment]
It should be 

    else {
    <text> Still in progress, It has not yet ended.</text>
    }

**Comment by kazekagegaara** [comment]
Done. Hope it works this time around.

**Comment by tidusjar** [comment]
Build success! :smile:  Thank you very much!

**Comment by kazekagegaara** [comment]
Cool. Hope you like the template, and thanks for letting me work on this!

**Pull request merged**
